---
- name: windows updates
  hosts: all
  gather_facts: yes
  tasks:
    - block:
      - name : searching for windows updates
        win_updates:
          category_names:
            - SecurityUpdates
            - CriticalUpdates
            - UpdateRollups
          state: searched
        #  become: yes
        #  become_method: runas
        #  become_user: azureuser
          log_path: C:\ansible_win_update.txt
        register: updates
      - name: Listing the available windows updates
        debug:
          msg: "{{ updates }}"
      - name : Installing the windows updates
        win_updates:
          category_names:
            - SecurityUpdates
            - CriticalUpdates
            - UpdateRollups
          state: installed
        #  become: yes
        #  become_method: runas
        #  become_user: azureuser
          log_path: C:\ansible_win_update_installed.txt
        register: updates
      - name: Status of above installation
        debug:
          msg: "{{ updates }}"
